### ISSUE TITLE
int() argument must be a string, a bytes-like object or a number, not 'NoneType'

### ISSUE THREAD

**Issue by cnscorpions** [FarjaalAhmad/django_tiktok_downloader#4]
It does not work well.

An error is thrown as stated aboe.

**Comment by FarjaalAhmad** [comment]
Hey, As I don't work on this project often that's why the sources should be down or something's changed. The thing is that I'm not getting time even for opening Github. I'll try to update it in the future. Sorry for the inconvenience.
